"""
This operator will create the source mesh for baking.
Source, being the original high resolution mesh only passed to the raytracer,
not the actual game mesh.
It will merge all visible geometry into a single giant mesh with all
modifiers applied for fast baking.
This needs to run AFTER creating the target meshes!
"""

# pylint: disable=import-error
import bpy
import bmesh
# pylint: enable=import-error

import numpy

from bake_v3.sbe_operator_ids import SBE_OP_SOURCE_MESHES
from bake_v3.sbe_logger import SBE_Logger
from bake_v3.sbe_util import set_node_group_value
from bake_v3.sbe_export_operator_base import SBE_ExportOperatorBase, SBE_Operator_Start_Result
from bake_v3.properties.sbe_object_props import SBE_ObjectProperties
from bake_v3.sbe_custom_properties import (
    SBE_OBJECT_BAKE_SOURCE_PROP, SBE_VERTEX_RANDOM_ATTRIBUTE
)
from bake_v3.sbe_name_parser import in_bake_source, only_in_bake_source
from bake_v3.sbe_mesh_util import (
    delete_faces_by_material_indices, ensure_unique_data,
    convert_to_mesh, find_physics_material_slot_indices,
    ensure_outside_normals, fast_join
)
from bake_v3.sbe_collection_util import (
    get_bake_collections, get_all_bake_collections, get_all_scene_bake_collection
)
from bake_v3.sbe_paths import NODE_GROUP_IS_GAME_MESH

def generate_source_object(
    context: bpy.types.Context,
    collection: bpy.types.Collection,
    index: int) -> bpy.types.Object:
    """Copy all objects relevant as a bake source and merge them into one"""
    objects: list[bpy.types.Object] = [i for i in collection.all_objects if in_bake_source(i)]
    copies: list[bpy.types.Object] = []
    with SBE_Logger("Duplicate"):
        for i in objects:
            obj: bpy.types.Object = i
            copy: bpy.types.Object = None
            if only_in_bake_source(obj):
                # use the original as it's not going to be in the target mesh
                copy = obj
            else:
                copy = obj.copy()
                obj.users_collection[0].objects.link(copy)
            ensure_unique_data(copy)
            copies.append(copy)

    convert_to_mesh(context, copies)

    with SBE_Logger("ensure_outside_normals"):
        for i in copies:
            obj: bpy.types.Object = i
            ensure_outside_normals(obj)

    # Remove physics materials, which might be generated by geo nodes.
    for i in copies:
        obj: bpy.types.Object = i
        physics_materials = find_physics_material_slot_indices(obj)
        delete_faces_by_material_indices(obj_mesh=obj.data, indices=physics_materials)

    with SBE_Logger("object_texture_coordinates"):
        # Create empty object stand ins for any texture coordinates relying on the objects original translation
        # This means, we'll have to duplicate the material, each time it's used!
        # If this ever turns into an issue, the coordinates could be passed via object properties to the shader.
        material_dupes = 0
        for i in copies:
            obj: bpy.types.Object = i
            for j in obj.material_slots:
                mat_slot: bpy.types.MaterialSlot = j
                if not mat_slot.material:
                    continue
                mat: bpy.types.Material = mat_slot.material
                if not mat.use_nodes or not mat.node_tree:
                    continue
                has_tex_coord_node = False
                for k in mat.node_tree.nodes:
                    if isinstance(k, bpy.types.ShaderNodeTexCoord):
                        has_tex_coord_node = True
                        break
                if not has_tex_coord_node:
                    continue
                empty: bpy.types.Object = None
                if mat.users != 1:
                    mat = mat.copy()
                    material_dupes += 1

                for k in mat.node_tree.nodes:
                    if not isinstance(k, bpy.types.ShaderNodeTexCoord):
                        continue
                    node: bpy.types.ShaderNodeTexCoord = k
                    if not empty:
                        # TODO name parsing visibility
                        empty = bpy.data.objects.new(name=f"/{obj.name}_{mat.name}", object_data=None)
                        obj.users_collection[0].objects.link(empty)
                        empty.matrix_local = obj.matrix_local
                    node.object = empty
                mat_slot.material = mat
        if 20 < material_dupes:
            SBE_Logger.error("Over 20 material duplicates created because of texture coordinate nodes using the object transform!")

    with SBE_Logger("setup_random"):
        # dumb approach to assign a random vertex attribute to all objects
        # regardless of the material needs it.
        # Once this gets to slow, maybe do the smarter approach
        for i in copies:
            obj: bpy.types.Object = i


            # The name changes for instances made real since in blender names are unique
            # so the result is unstable on export, for now let's try the position instead
            # random = abs(hash(obj.name)) / 100000000000000000 % 1.0
            # we also need 32 bit floating point precision here so it matches the realtime preview
            random = numpy.float32(numpy.float32(numpy.float32(numpy.float32(obj.location[0] + obj.location[1]) + obj.location[2]) * 10.0) % 1.0)

            bm = bmesh.new()
            bm.from_mesh(obj.data)
            target_attribute_layer: bmesh.types.BMLayerItem = None
            if SBE_VERTEX_RANDOM_ATTRIBUTE not in bm.verts.layers.float:
                target_attribute_layer = bm.verts.layers.float.new(SBE_VERTEX_RANDOM_ATTRIBUTE)
            else:
                # Random explicitly set by modifier or user
                continue
                # target_attribute_layer = bm.verts.layers.float[SBE_VERTEX_RANDOM_ATTRIBUTE]

            for i in bm.verts:
                vert: bmesh.types.BMVert = i
                vert[target_attribute_layer] = random
            bm.to_mesh(obj.data)
            bm.free()

    # make a new mesh, one per bake collection containing all the geometry
    source_mesh = bpy.data.meshes.new(f"source_{index}_mesh")
    source_object = bpy.data.objects.new(name=f"source_{index}_object", object_data=source_mesh)
    source_object[SBE_OBJECT_BAKE_SOURCE_PROP] = index
    context.scene.collection.objects.link(source_object)

    fast_join(source_object, copies)
    # join_complete(source_object, copies, context)

    return source_object


class SBE_GenerateSourceMeshes(SBE_ExportOperatorBase):
    """Generate bake source meshes"""
    bl_idname = SBE_OP_SOURCE_MESHES
    bl_label = "Generate source meshes"
    bpl_auto_load = True

    def execute_internal(self, context: bpy.types.Context, start: SBE_Operator_Start_Result):
        set_node_group_value(NODE_GROUP_IS_GAME_MESH, False)

        # Make sure none of the physics objects etc affect the render
        for i in context.scene.objects:
            obj: bpy.types.Object = i
            if obj.type != 'LIGHT' and not in_bake_source(obj):
                obj.hide_render = True

        bake_collections = get_bake_collections(context)
        all_bake_collections_scene = get_all_scene_bake_collection(context)
        all_bake_collections = get_all_bake_collections()

        sources: list[bpy.types.Object] = []

        for i, collection in enumerate(all_bake_collections):
            if collection not in all_bake_collections_scene:
                continue # skip over bake collections in another scene, can't bake across scenes

            if collection in bake_collections:
                sources.append(generate_source_object(context=context, collection=collection, index=i))

        for i in context.collection.all_objects[:]:
            obj: bpy.types.Object = i
            props: SBE_ObjectProperties = SBE_ObjectProperties.get(obj)
            if props.visibility == 'DISCARD':
                obj.hide_render = True

        # Joining sources is increasing performance by 2x
        # Maybe we could do some magic in the blender source
        # to allow fast bakes without joining sources?
        if len(sources) != 0:
            single_source_mesh = bpy.data.meshes.new("source_joined_mesh")
            single_source_object = bpy.data.objects.new(name="source_joined_object", object_data=single_source_mesh)
            single_source_object[SBE_OBJECT_BAKE_SOURCE_PROP] = 0
            fast_join(single_source_object, sources)
            context.scene.collection.objects.link(single_source_object)
            # join_complete(sources[0], sources, context)
